# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Tony Mason
title: Consultant
email: tony@wamason.com
website: wamason-com.github.io

# Social links
twitter_username: fsgeek
github_username:  fsgeek
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: tonymason2
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm Tony Mason  

  I am most skilled in: Explaining complex concepts in simpler terms

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experience
experience_content: | # paragraphs allowed again

UBC
OSR
FORE Systems
Transarc
Stanford

# Education Section
educaton_title: Education | # paragraphs allowed

UBC
Georgia Institute of Technology
University of Chicago


# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Climbing
#   - Fortnite
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-leap-day
